version: 2

models:
  - name: dim_zones
    description: >
      List of unique zones identified by locationId 
  
  - name: dm_monthly_zone_revenue
    description: >
      Aggregated table of all taxi trips corresponding to both service zones 
    columns:
      - name: revenue_monthly_total_amount
        description: Monthly sum of the total_amount of the fare charged for the trip per pickup zone, month and service 
        tests:
          - not_null:
              severity : warn 
          

  - name: fact_trips
    description: ""
    columns:
      - name: tripid
        data_type: string
        description: ""

      - name: vendorid
        data_type: int64
        description: ""

      - name: service_type
        data_type: string
        description: ""

      - name: ratecodeid
        data_type: float64
        description: ""

      - name: pulocationid
        data_type: int64
        description: ""

      - name: pickup_borough
        data_type: string
        description: ""

      - name: pickup_zone
        data_type: string
        description: ""

      - name: dolocationid
        data_type: int64
        description: ""

      - name: dropoff_borough
        data_type: string
        description: ""

      - name: dropoff_zone
        data_type: string
        description: ""

      - name: lpep_pickup_datetime
        data_type: date
        description: ""

      - name: lpep_dropoff_datetime
        data_type: date
        description: ""

      - name: store_and_fwd_flag
        data_type: string
        description: ""

      - name: passenger_count
        data_type: float64
        description: ""

      - name: trip_distance
        data_type: float64
        description: ""

      - name: trip_type
        data_type: float64
        description: ""

      - name: fare_amount
        data_type: float64
        description: ""

      - name: extra
        data_type: float64
        description: ""

      - name: mta_tax
        data_type: float64
        description: ""

      - name: tip_amount
        data_type: float64
        description: ""

      - name: tolls_amount
        data_type: float64
        description: ""

      - name: ehail_fee
        data_type: numeric
        description: ""

      - name: improvement_surcharge
        data_type: float64
        description: ""

      - name: total_amount
        data_type: float64
        description: ""

      - name: payment_type
        data_type: float64
        description: ""

      - name: payment_type_descriptive
        data_type: string
        description: ""
